### ISSUE TITLE
不知道你这些命令讲解基于Go的哪个版本，什么系统

### ISSUE THREAD

**Issue by polaris1119** [hyper-carrot/go_command_tutorial#12]
比如，go build 那块，-a 参数，我在mac下，从 go1.1 到 1.4，执行结果跟你说的完全不一样。

而且，你对 -a 的解释：*强行对所有涉及到的代码包（包括标准库中的代码包）进行重新构建，即使它们已经是最新的了。*

我的理解，-a 只是说会重新编译你项目的文件，不会编译标准库的，要不然有点乱了，实际上，我试验了，也不会编译标准库

**Comment by hyper-carrot** [comment]
是基于1.3版本的

**Comment by hyper-carrot** [comment]
你可以改动下标准库中的代码试验一下？

**Comment by hyper-carrot** [comment]
go build -a -work -n

**Comment by hyper-carrot** [comment]
经我和@polaris1119 的联合试验和确认，在Go 1.4.x版本中，`-a`标签不会导致标准库中代码包的重新编译。而在Go 1.3.x版本中，其行为恰恰相反。
