### ISSUE TITLE
使用go tool pprof工具输出的结果是空

### ISSUE THREAD

**Issue by workhardcc** [hyper-carrot/go_command_tutorial#22]
您好，为啥我在main函数里添加了如下代码后，用go tool pprof工具输出的结果是空啊？生成的prof文件只有64B...
func main(){
flag.Parse()
    if *cpuprofile != "" {
        // 根据命令行指定文件名创建 profile 文件
        f, err := os.Create(*cpuprofile)
        if err != nil {
            log.Fatal(err)
        }
        // 开启 CPU profiling
        pprof.StartCPUProfile(f)
        defer pprof.StopCPUProfile()
    }
.
.
.
}
输出结果如下

>  go tool pprof metrics_prof mytest.prof
> Entering interactive mode (type "help" for commands)
> (pprof) list
> Total: 0
> (pprof) top
> 0 of 0 total (    0%)
>       flat  flat%   sum%        cum   cum%
> (pprof) q
>

**Comment by hyper-carrot** [comment]
两种可能：程序基本没用CPU，或者你采样的时间太短。

**Comment by hyper-carrot** [comment]
这个issue我暂且关闭。如有需要你可以再次开启。

**Comment by workhardcc** [comment]
谢谢！
